spring:
  jwt:
    secret: my-super-secret-key-for-jwt-123456789
  application:
    name: yud20
  datasource:
    url: jdbc:mysql://localhost:3306/vecanhacdb
    username: root
    password: duy123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: blackjavk12@gmail.com
    password: ldczyiowrlspeezq # <- là mật khẩu ứng dụng 16 ký tự
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

